<%@ Page 
 Language="C#" 
 debug=true
 Inherits="WordEngineering.ContactMaintenancePage"
%>

<!--
	2016-11-27 	For the will of the Carbon; is the copy. 2005-07-31 ImageCarbon database; ImageCarbonForm database object.
	2014-08-24 	stackoverflow.com/questions/4793955/how-to-add-a-confirm-delete-option-in-asp-net-gridview
	2015-08-11	SelectCommandType="StoredProcedure" SelectCommand="dbo.uspContactSelect"
	2015-08-12	SelectCommandType="StoredProcedure" SelectCommand="dbo.usp_ContactMaintenanceQuery"
	2016-04-14	ContactRelated. I help, I become. Christian Bailey. Morris Cerullo.
	2016-04-14	ContactBuild.bat
	2016-04-14	ContactBuild.mak
	2017-08-13	Convert sequenceOrderID to tableName ID.
-->

<%@ Register Assembly="UtilityProtocol" Namespace="WordEngineering" TagPrefix="UtilityProtocol" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" 
"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" >
 <head runat="Server" id="HeadContact">
  <title runat="Server" id="TitleContact">Contact</title>
  <!--
	2014-08-24 http://stackoverflow.com/questions/4793955/how-to-add-a-confirm-delete-option-in-asp-net-gridview
  -->
 </head>
 <body runat="server" id="BodyContact">
  <asp:Panel
   runat="server"
   id="PanelContact"
  >
   <form 
    ID="FormContact" 
    runat="server"
    enctype="multipart/form-data"    
    autocomplete="on"
    defaultbutton="ButtonSubmit"
    defaultfocus="TextBoxFirstName"
   >
    <div align="center">
		Search Query
		<asp:TextBox
		 runat="Server"
		 ID="TextBoxQuery"
		 TabIndex="1"
		/>        
		<asp:Button runat="server" id="ButtonSubmit"  onclick="ButtonSubmit_Click"  Text="Submit" TabIndex="2" />
		<asp:Button runat="server" id="ButtonReset"   onclick="ButtonReset_Click"   Text="Reset"  TabIndex="3" />
    </div>

    <div align="center">
        <asp:Label
         runat="server"       
         id="LabelEmailRecipient"
         Text="Email Recipient:"
         AccessKey="E"
         AssociatedControlId="TextBoxEmailRecipient"
        />
        <asp:TextBox
         runat="Server"
         ID="TextBoxEmailRecipient"
         TabIndex="21"
        />
        <asp:Button runat="server" id="ButtonEmail"  onclick="ButtonEmail_Click"  Text="Email" TabIndex="22" />
	</div>
	
    <table align="center" border="0">
     <tbody>
      <tr align="center">
       <td>
        <asp:SqlDataSource
         ID="SqlDataSourceContact"
         Runat="server"
         ConnectionString="<%$ ConnectionStrings:WordEngineering %>"
         DeleteCommand="DELETE Contact WHERE ContactID = @ContactID"
         InsertCommand="EXEC uspContactInsert @ContactID, @dated, @title, @firstName, @lastName, @otherName, @company, @commentary"
		 
		 SelectCommandType="StoredProcedure"
		 SelectCommand="dbo.usp_ContactMaintenanceQuery" 
         OnSelected="SqlDataSource_Selected"

         UpdateCommand="UPDATE Contact SET dated = @dated, firstName = @firstName, lastName = @lastName, otherName = @otherName, title = @title, company = @company, commentary = @commentary WHERE ContactID = @ContactID"
        >
         <insertparameters>
          <asp:parameter name="ContactID" ConvertEmptyStringToNull=true Type="Int32" />
          <asp:parameter name="dated" ConvertEmptyStringToNull=true Type="DateTime" />
          <asp:parameter name="title" ConvertEmptyStringToNull=true Type="string" />
          <asp:parameter name="firstName" ConvertEmptyStringToNull=true Type="string" />
          <asp:parameter name="lastName" ConvertEmptyStringToNull=true Type="string" />
          <asp:parameter name="otherName" ConvertEmptyStringToNull=true Type="string" />
          <asp:parameter name="company" ConvertEmptyStringToNull=true Type="string" />
          <asp:parameter name="commentary" ConvertEmptyStringToNull=true Type="string" />
         </insertparameters>
         <selectparameters>
			<asp:controlparameter name="query" controlid="TextBoxQuery" PropertyName="Text" ConvertEmptyStringToNull=true Type="string" Direction="Input" DefaultValue = "|" />
         </selectparameters>

		</asp:SqlDataSource>

        <asp:GridView
         id="GridViewContact" 
         runat="server" 
         AllowPaging=True
         AllowSorting=True 
         AutoGenerateColumns=False
         AutoGenerateDeleteButton=True
         AutoGenerateEditButton=True
         AutoGenerateSelectButton=True        
         DataKeyNames="ContactID"
         DataSourceID="SqlDataSourceContact"
         OnPreRender="GridView_PreRender"
         OnRowUpdated="GridView_RowUpdated"
         SelectedIndex=0
         ShowFooter=True
        >
         <HeaderStyle
          BackColor='#CCCC99'/>

         <RowStyle
          BackColor='#eeeeee'/>
			
         <AlternatingRowStyle
          BackColor='#ffffe8'/>

         <Columns>
               
          <asp:TemplateField
           HeaderText="First Name"
           SortExpression="FirstName"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewContactItemTemplateFirstName" 
             Text='<%# Eval("FirstName") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactEditItemTemplateFirstName" 
             Text='<%# Bind("FirstName") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactFooterTemplateFirstName"
             Text='<%# Bind("FirstName") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="Last Name"
           SortExpression="LastName"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewContactItemTemplateLastName" 
             Text='<%# Eval("LastName") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactEditItemTemplateLastName" 
             Text='<%# Bind("LastName") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactFooterTemplateLastName"
             Text='<%# Bind("LastName") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="Other Name"
           SortExpression="OtherName"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewContactItemTemplateOtherName" 
             Text='<%# Eval("OtherName") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactEditItemTemplateOtherName" 
             Text='<%# Bind("OtherName") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactFooterTemplateOtherName"
             Text='<%# Bind("OtherName") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="Title"
           SortExpression="Title"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewContactItemTemplateTitle" 
             Text='<%# Eval("Title") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactEditItemTemplateTitle" 
             Text='<%# Bind("Title") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactFooterTemplateTitle"
             Text='<%# Bind("Title") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="Company"
           SortExpression="Company"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewContactItemTemplateCompany" 
             Text='<%# Eval("Company") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactEditItemTemplateCompany" 
             Text='<%# Bind("Company") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactFooterTemplateCompany"
             Text='<%# Bind("Company") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="Commentary"
           SortExpression="Commentary"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewContactItemTemplateCommentary" 
             Text='<%# Eval("Commentary") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactEditItemTemplateCommentary" 
             Text='<%# Bind("Commentary") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox
                Runat="Server"
                id="TextBoxGridViewContactFooterTemplateCommentary"
                Text='<%# Bind("Commentary") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="Dated"
           SortExpression="Dated"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewContactItemTemplateDated" 
             Text='<%# Eval("Dated", "{0:s}") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactEditItemTemplateDated" 
             Text='<%# Bind("Dated") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactFooterTemplateDated"
             Text='<%# Bind("Dated") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="ContactID"
           SortExpression="ContactID"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewContactItemTemplateContactID" 
             Text='<%# Eval("ContactID") %>'
            />
           </ItemTemplate>
<%--
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactEditItemTemplateContactID" 
             Text='<%# Bind("ContactID") %>'
            />
           </EditItemTemplate>
--%>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactFooterTemplateContactID"
             Text='<%# Bind("ContactID") %>'
            />
            <asp:Button 
             Runat="Server"           
             ID="ButtonGridViewContactFooterTemplateAdd"
             OnClick="GridViewContactInsert"
             Text="Add"
            />
           </FooterTemplate>
          </asp:TemplateField>
         
         </Columns>
         <pagersettings 
          mode="Numeric"
          position="Bottom"           
          pagebuttoncount="10"
         />
         <pagerstyle 
          backcolor="LightBlue"
          height="30px"
          verticalalign="Bottom"
          horizontalalign="Center"
         />
        </asp:GridView>
       </td>
      </tr>
     </tbody>
    </table>

    <table align="center" border="0">
     <tbody> 
      <tr align="center">
       <td align="center">
        <asp:SqlDataSource
         ID="SqlDataSourceContactEmail"
         Runat="server"
         ConnectionString="<%$ ConnectionStrings:WordEngineering %>"
         DeleteCommand="DELETE ContactEmail WHERE ContactEmailID = @ContactEmailID"
         InsertCommand="EXEC uspContactEmailInsert @ContactEmailID, @dated, @ContactID, @emailAddress"
         SelectCommand="SELECT ContactEmailID, dated, emailAddress FROM ContactEmail WHERE ContactID = @ContactID ORDER BY Dated DESC, ContactEmailID DESC"
         UpdateCommand="UPDATE ContactEmail SET dated = @dated, emailAddress = @emailAddress WHERE ContactEmailID = @ContactEmailID"
        >
         <insertparameters>
          <asp:parameter name="ContactEmailID" ConvertEmptyStringToNull=true Type="Int32" />
          <asp:parameter name="dated" ConvertEmptyStringToNull=true Type="DateTime" />
          <asp:ControlParameter Name="ContactID" ControlId="GridViewContact" PropertyName="SelectedValue" />
          <asp:parameter name="emailAddress" ConvertEmptyStringToNull=true Type="string" />
         </insertparameters>
         <selectparameters>
          <asp:ControlParameter Name="ContactID" ControlId="GridViewContact" PropertyName="SelectedValue" />
         </selectparameters>
        </asp:SqlDataSource>

        <asp:GridView
         id="GridViewContactEmail" 
         runat="server" 
         AllowPaging=True
         AllowSorting=True 
         AutoGenerateColumns=False
         AutoGenerateDeleteButton=True
         AutoGenerateEditButton=True
         AutoGenerateSelectButton=True        
         DataKeyNames="ContactEmailID"
         DataSourceID="SqlDataSourceContactEmail"
         OnPreRender="GridView_PreRender"
         OnRowUpdated="GridView_RowUpdated"
         SelectedIndex=0        
         ShowFooter=True
        >
         <HeaderStyle
          BackColor='#CCCC99'/>

         <RowStyle
          BackColor='#eeeeee'/>
			
         <AlternatingRowStyle
          BackColor='#ffffe8'/>

         <Columns>
               
          <asp:TemplateField
           HeaderText="E-mail"
           SortExpression="EmailAddress"
          >
           <ItemTemplate>
            <asp:HyperLink
             Runat="Server"
             id="HyperLinkGridViewContactEmailItemTemplateEmailAddress" 
             NavigateUrl='<%# "mailto:" + Eval("EmailAddress").ToString() %>'
             Text='<%# Eval("EmailAddress") %>'
             Target="_blank"
            />  
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactEmailEditItemTemplateEmailAddress" 
             Text='<%# Bind("EmailAddress") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactEmailFooterTemplateEmailAddress"
             Text='<%# Bind("EmailAddress") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="Dated"
           SortExpression="Dated"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewContactEmailItemTemplateDated" 
             Text='<%# Eval("Dated", "{0:s}") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactEmailEditItemTemplateDated" 
             Text='<%# Bind("Dated") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactEmailFooterTemplateDated"
             Text='<%# Bind("Dated") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="ContactEmailID"
           SortExpression="ContactEmailID"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewContactEmailItemTemplateContactEmailID" 
             Text='<%# Eval("ContactEmailID") %>'
            />
           </ItemTemplate>
<%--
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactEmailEditItemTemplateContactEmailID" 
             Text='<%# Bind("ContactEmailID") %>'
            />
           </EditItemTemplate>
--%>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactEmailFooterTemplateContactEmailID"
             Text='<%# Bind("ContactEmailID") %>'
            />
            <asp:Button 
             Runat="Server"           
             ID="ButtonGridViewContactEmailFooterTemplateAdd"
             OnClick="GridViewContactEmailInsert"
             Text="Add"
            />
           </FooterTemplate>
          </asp:TemplateField>
         
         </Columns>
         <pagersettings 
          mode="Numeric"
          position="Bottom"           
          pagebuttoncount="10"
         />
         <pagerstyle 
          backcolor="LightBlue"
          height="30px"
          verticalalign="Bottom"
          horizontalalign="Center"
         />
        </asp:GridView>
       </td>
      </tr>
     </tbody>    
    </table>

    <table align="center" border="0">
     <tbody> 
      <tr align="center">
       <td align="center">
          <asp:FormView 
           runat="server"
           id="FormViewContactEmail"
           AllowPaging="true"
           DataKeyNames="ContactEmailID"
           DataSourceID="SqlDataSourceContactEmail"
           DefaultMode="Insert"
           OnItemInserted="FormView_ItemInserted"

           Visible=false
          >
           <InsertItemTemplate>
            <table>
             <theader>
              <tr>
               <th>Email Address</th>
               <th>Dated</th>
               <th>ContactEmailID</th>
              </tr>
             </theader>
             <tbody>
              <tr>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewContactEmailInsertItemTemplateEmailAddress" 
                 Text='<%# Bind("EmailAddress") %>'
                />
               </td>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewContactEmailInsertItemTemplateDated" 
                 Text='<%# Bind("Dated") %>'
                />
               </td>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewContactEmailInsertItemTemplateContactEmailID" 
                 Text='<%# Bind("ContactEmailID") %>'
                />
               </td>
               <td>
                <asp:Button 
                 runat="server"
                 id="ButtonFormViewContactEmail"  
                 onclick="ButtonFormViewContactEmailInsert_Click"
                 Text="Add"
                />
                <%--
                 <asp:linkbutton 
                 runat="server"
                 id="LinkButtonInsert"
                 text="Insert"
                 commandname="Insert"
                />
                <asp:linkbutton 
                 runat="server"
                 id="LinkButtonCancel"
                 text="Cancel"
                 commandname="Cancel"
                />
                --%>
               </td>
              </tr> 
             </tbody>
            </table>       
           </InsertItemTemplate>
          </asp:FormView>
       </td>
      </tr>
     </tbody>    
    </table>

    <table align="center" border="0">
     <tbody> 
      <tr align="center">
       <td align="center">
        <asp:SqlDataSource
         ID="SqlDataSourceContactURI"
         Runat="server"
         ConnectionString="<%$ ConnectionStrings:WordEngineering %>"
         DeleteCommand="DELETE ContactURI WHERE ContactURIID = @ContactURIID"
         InsertCommand="EXEC uspContactURIInsert @ContactURIID, @dated, @ContactID, @internetAddress"
         SelectCommand="SELECT ContactURIID, dated, internetAddress FROM ContactURI WHERE ContactID = @ContactID ORDER BY Dated DESC, ContactURIID DESC"
         UpdateCommand="UPDATE ContactURI SET dated = @dated, internetAddress = @internetAddress WHERE ContactURIID = @ContactURIID"
        >
         <insertparameters>
          <asp:parameter name="ContactURIID" ConvertEmptyStringToNull=true Type="Int32" />
          <asp:parameter name="dated" ConvertEmptyStringToNull=true Type="DateTime" />
          <asp:ControlParameter Name="ContactID" ControlId="GridViewContact" PropertyName="SelectedValue" />
          <asp:parameter name="internetAddress" ConvertEmptyStringToNull=true Type="string" />
         </insertparameters>
         <selectparameters>
          <asp:ControlParameter Name="ContactID" ControlId="GridViewContact" PropertyName="SelectedValue" />
         </selectparameters>
        </asp:SqlDataSource>

        <asp:GridView
         id="GridViewContactURI" 
         runat="server" 
         AllowPaging=True
         AllowSorting=True 
         AutoGenerateColumns=False
         AutoGenerateDeleteButton=True
         AutoGenerateEditButton=True
         AutoGenerateSelectButton=True        
         DataKeyNames="ContactURIID"
         DataSourceID="SqlDataSourceContactURI"
         OnPreRender="GridView_PreRender"
         OnRowUpdated="GridView_RowUpdated"
         SelectedIndex=0        
         ShowFooter=True
        >
         <HeaderStyle
          BackColor='#CCCC99'/>

         <RowStyle
          BackColor='#eeeeee'/>
			
         <AlternatingRowStyle
          BackColor='#ffffe8'/>

         <Columns>
               
          <asp:TemplateField
           HeaderText="URI"
           SortExpression="InternetAddress"
          >
           <ItemTemplate>
            <asp:HyperLink
             Runat="Server"
             id="HyperLinkGridViewContactURIItemTemplateInternetAddress" 
             NavigateUrl='<%# UtilityProtocol.PrefixProtocol( Eval("InternetAddress").ToString() ) %>'
             Text='<%# Eval("InternetAddress") %>'
             Target="_blank"
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactURIEditItemTemplateInternetAddress" 
             Text='<%# Bind("InternetAddress") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactURIFooterTemplateInternetAddress"
             Text='<%# Bind("InternetAddress") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="Dated"
           SortExpression="Dated"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewContactURIItemTemplateDated" 
             Text='<%# Eval("Dated", "{0:s}") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactURIEditItemTemplateDated" 
             Text='<%# Bind("Dated") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactURIFooterTemplateDated"
             Text='<%# Bind("Dated") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="ContactURIID"
           SortExpression="ContactURIID"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewContactURIItemTemplateContactURIID" 
             Text='<%# Eval("ContactURIID") %>'
            />
           </ItemTemplate>
<%--
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactURIEditItemTemplateContactURIID" 
             Text='<%# Bind("ContactURIID") %>'
            />
           </EditItemTemplate>
--%>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactURIFooterTemplateContactURIID"
             Text='<%# Bind("ContactURIID") %>'
            />
            <asp:Button 
             Runat="Server"           
             ID="ButtonGridViewContactURIFooterTemplateAdd"
             OnClick="GridViewContactURIInsert"
             Text="Add"
            />
           </FooterTemplate>
          </asp:TemplateField>
         
         </Columns>
         <pagersettings 
          mode="Numeric"
          position="Bottom"           
          pagebuttoncount="10"
         />
         <pagerstyle backcolor="LightBlue"
          height="30px"
          verticalalign="Bottom"
          horizontalalign="Center"
         />
        </asp:GridView>
       </td>
      </tr>
     </tbody>    
    </table>

    <table align="center" border="0">
     <tbody> 
      <tr align="center">
       <td align="center">
          <asp:FormView 
           runat="server"
           id="FormViewContactURI"
           AllowPaging="true"
           DataKeyNames="ContactURIID"
           DataSourceID="SqlDataSourceContactURI"
           DefaultMode="Insert"
           OnItemInserted="FormView_ItemInserted"

           Visible=false
          >
           <InsertItemTemplate>
            <table>
             <theader>
              <tr>
               <th>Internet Address</th>
               <th>Dated</th>
               <th>ContactURIID</th>
              </tr>
             </theader>
             <tbody>
              <tr>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewContactURIInsertItemTemplateInternetAddress" 
                 Text='<%# Bind("InternetAddress") %>'
                />
               </td>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewContactURIInsertItemTemplateDated" 
                 Text='<%# Bind("Dated") %>'
                />
               </td>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewContactURIInsertItemTemplateContactURIID" 
                 Text='<%# Bind("ContactURIID") %>'
                />
               </td>
               <td>
                <asp:Button 
                 runat="server"
                 id="ButtonFormViewContactURI"  
                 onclick="ButtonFormViewContactURIInsert_Click"
                 Text="Add"
                />
                <%--
                 <asp:linkbutton 
                 runat="server"
                 id="LinkButtonInsert"
                 text="Insert"
                 commandname="Insert"
                />
                <asp:linkbutton 
                 runat="server"
                 id="LinkButtonCancel"
                 text="Cancel"
                 commandname="Cancel"
                />
                --%>
               </td>
              </tr> 
             </tbody>
            </table>       
           </InsertItemTemplate>
          </asp:FormView>
       </td>
      </tr>
     </tbody>    
    </table>

    <table align="center" border="0">
     <tbody> 
      <tr align="center">
       <td align="center">
        <asp:SqlDataSource
         ID="SqlDataSourceTelephone"
         Runat="server"
         ConnectionString="<%$ ConnectionStrings:WordEngineering %>"
         DeleteCommand="DELETE Telephone WHERE telephoneID = @telephoneID"
         InsertCommand="EXEC uspTelephoneInsert @telephoneID, @dated, @ContactID, @telephoneNo, @telephoneLocation"
         SelectCommand="SELECT telephoneID, dated, telephoneNo, telephoneLocation FROM Telephone WHERE ContactID = @ContactID ORDER BY Dated DESC, telephoneID DESC"
         UpdateCommand="UPDATE Telephone SET dated = @dated, telephoneNo = @telephoneNo, telephoneLocation = @telephoneLocation WHERE telephoneID = @telephoneID"
        >
         <insertparameters>
          <asp:parameter name="telephoneID" ConvertEmptyStringToNull=true Type="Int32" />
          <asp:parameter name="dated" ConvertEmptyStringToNull=true Type="DateTime" />
          <asp:ControlParameter Name="ContactID" ControlId="GridViewContact" PropertyName="SelectedValue" />
          <asp:parameter name="telephoneNo" ConvertEmptyStringToNull=true Type="string" />
          <asp:parameter name="telephoneLocation" ConvertEmptyStringToNull=true Type="string" />
         </insertparameters>
         <selectparameters>
          <asp:ControlParameter Name="ContactID" ControlId="GridViewContact" PropertyName="SelectedValue" />
         </selectparameters>
        </asp:SqlDataSource>

        <asp:GridView
         id="GridViewTelephone" 
         runat="server" 
         AllowPaging=True
         AllowSorting=True 
         AutoGenerateColumns=False
         AutoGenerateDeleteButton=True
         AutoGenerateEditButton=True
         AutoGenerateSelectButton=True        
         DataKeyNames="telephoneID"
         DataSourceID="SqlDataSourceTelephone"
         OnPreRender="GridView_PreRender"
         OnRowUpdated="GridView_RowUpdated"
         SelectedIndex=0        
         ShowFooter=True
        >
         <HeaderStyle
          BackColor='#CCCC99'/>

         <RowStyle
          BackColor='#eeeeee'/>
			
         <AlternatingRowStyle
          BackColor='#ffffe8'/>

         <Columns>

          <asp:TemplateField
           HeaderText="Telephone No"
           SortExpression="TelephoneNo"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewTelephoneItemTemplateTelephoneNo" 
             Text='<%# Eval("TelephoneNo") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewTelephoneEditItemTemplateTelephoneNo" 
             Text='<%# Bind("TelephoneNo") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewTelephoneFooterTemplateTelephoneNo"
             Text='<%# Bind("TelephoneNo") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="Telephone Location"
           SortExpression="TelephoneLocation"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewTelephoneItemTemplateTelephoneLocation" 
             Text='<%# Eval("TelephoneLocation") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewTelephoneEditItemTemplateTelephoneLocation" 
             Text='<%# Bind("TelephoneLocation") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewTelephoneFooterTemplateTelephoneLocation"
             Text='<%# Bind("TelephoneLocation") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="Dated"
           SortExpression="Dated"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewTelephoneItemTemplateDated" 
             Text='<%# Eval("Dated", "{0:s}") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewTelephoneEditItemTemplateDated" 
             Text='<%# Bind("Dated") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewTelephoneFooterTemplateDated"
             Text='<%# Bind("Dated") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="TelephoneID"
           SortExpression="TelephoneID"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewTelephoneItemTemplateTelephoneID" 
             Text='<%# Eval("TelephoneID") %>'
            />
           </ItemTemplate>
<%--
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewTelephoneEditItemTemplateTelephoneID" 
             Text='<%# Bind("TelephoneID") %>'
            />
           </EditItemTemplate>
--%>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewTelephoneFooterTemplateTelephoneID"
             Text='<%# Bind("TelephoneID") %>'
            />
            <asp:Button 
             Runat="Server"           
             ID="ButtonGridViewTelephoneFooterTemplateAdd"
             OnClick="GridViewTelephoneInsert"
             Text="Add"
            />
           </FooterTemplate>
          </asp:TemplateField>
         
         </Columns>
         <pagersettings 
          mode="Numeric"
          position="Bottom"           
          pagebuttoncount="10"
         />
         <pagerstyle 
          backcolor="LightBlue"
          height="30px"
          verticalalign="Bottom"
          horizontalalign="Center"
         />
        </asp:GridView>
       </td>
      </tr>
     </tbody>    
    </table>

    <table align="center" border="0">
     <tbody> 
      <tr align="center">
       <td align="center">
          <asp:FormView 
           runat="server"
           id="FormViewTelephone"
           AllowPaging="true"
           DataKeyNames="TelephoneID"
           DataSourceID="SqlDataSourceTelephone"
           DefaultMode="Insert"
           OnItemInserted="FormView_ItemInserted"

           Visible=false
          >
           <InsertItemTemplate>
            <table>
             <theader>
              <tr>
               <th>Telephone No</th>
               <th>Telephone Location</th>              
               <th>Dated</th>
               <th>TelephoneID</th>
              </tr>
             </theader>
             <tbody>
              <tr>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewTelephoneInsertItemTemplateTelephoneNo" 
                 Text='<%# Bind("TelephoneNo") %>'
                />
               </td>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewTelephoneInsertItemTemplateTelephoneLocation" 
                 Text='<%# Bind("TelephoneLocation") %>'
                />
               </td>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewTelephoneInsertItemTemplateDated" 
                 Text='<%# Bind("Dated") %>'
                />
               </td>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewTelephoneInsertItemTemplateTelephoneID" 
                 Text='<%# Bind("TelephoneID") %>'
                />
               </td>
               <td>
                <asp:Button 
                 runat="server"
                 id="ButtonFormViewTelephone"  
                 onclick="ButtonFormViewTelephoneInsert_Click"
                 Text="Add"
                />
                <%--
                <asp:linkbutton 
                 runat="server"
                 id="LinkButtonInsert"
                 text="Insert"
                 commandname="Insert"
                />
                <asp:linkbutton 
                 runat="server"
                 id="LinkButtonCancel"
                 text="Cancel"
                 commandname="Cancel"
                />
                --%>
               </td>
              </tr> 
             </tbody>
            </table>       
           </InsertItemTemplate>
          </asp:FormView>
       </td>
      </tr>
     </tbody>    
    </table>

    <table align="center" border="0">
     <tbody> 
      <tr align="center">
       <td align="center">
        <asp:SqlDataSource
         ID="SqlDataSourceStreetAddress"
         Runat="server"
         ConnectionString="<%$ ConnectionStrings:WordEngineering %>"
         DeleteCommand="DELETE StreetAddress WHERE streetAddressID = @streetAddressID"
         InsertCommand="EXEC uspStreetAddressInsert @streetAddressID, @dated, @ContactID, @addressLine1, @city, @state, @zipCode, @country"
         SelectCommand="SELECT streetAddressID, dated, addressLine1, city, state, zipCode, country FROM StreetAddress WHERE ContactID = @ContactID ORDER BY Dated DESC, streetAddressID DESC "
         UpdateCommand="UPDATE StreetAddress SET dated = @dated, addressLine1 = @addressLine1, city = @city, state = @state, zipCode = @zipCode, country = @country WHERE streetAddressID = @streetAddressID"
        >
         <insertparameters>
          <asp:parameter name="streetAddressID" ConvertEmptyStringToNull=true Type="Int32" />
          <asp:parameter name="dated" ConvertEmptyStringToNull=true Type="DateTime" />
          <asp:ControlParameter Name="ContactID" ControlId="GridViewContact" PropertyName="SelectedValue" />
          <asp:parameter name="addressLine1" ConvertEmptyStringToNull=true Type="string" />
          <asp:parameter name="city" ConvertEmptyStringToNull=true Type="string" />
          <asp:parameter name="state" ConvertEmptyStringToNull=true Type="string" />
          <asp:parameter name="zipCode" ConvertEmptyStringToNull=true Type="string" />
          <asp:parameter name="country" ConvertEmptyStringToNull=true Type="string" />
         </insertparameters>
         <selectparameters>
          <asp:ControlParameter Name="ContactID" ControlId="GridViewContact" PropertyName="SelectedValue" />
         </selectparameters>
        </asp:SqlDataSource>

        <asp:GridView
         id="GridViewStreetAddress" 
         runat="server" 
         AllowPaging=True
         AllowSorting=True 
         AutoGenerateColumns=False
         AutoGenerateDeleteButton=True
         AutoGenerateEditButton=True
         AutoGenerateSelectButton=True        
         DataKeyNames="streetAddressID"
         DataSourceID="SqlDataSourceStreetAddress"
         OnPreRender="GridView_PreRender"
         OnRowUpdated="GridView_RowUpdated"
         SelectedIndex=0        
         ShowFooter=True
        >
         <HeaderStyle
          BackColor='#CCCC99'/>

         <RowStyle
          BackColor='#eeeeee'/>
			
         <AlternatingRowStyle
          BackColor='#ffffe8'/>

         <Columns>

          <asp:TemplateField
           HeaderText="Address Line 1"
           SortExpression="AddressLine1"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewStreetAddressItemTemplateAddressLine1" 
             Text='<%# Eval("AddressLine1") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewStreetAddressEditItemTemplateAddressLine1" 
             Text='<%# Bind("AddressLine1") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewStreetAddressFooterTemplateAddressLine1"
             Text='<%# Bind("AddressLine1") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="City"
           SortExpression="City"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewStreetAddressItemTemplateCity" 
             Text='<%# Eval("City") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewStreetAddressEditItemTemplateCity" 
             Text='<%# Bind("City") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewStreetAddressFooterTemplateCity"
             Text='<%# Bind("City") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="State"
           SortExpression="State"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewStreetAddressItemTemplateState" 
             Text='<%# Eval("State") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewStreetAddressEditItemTemplateState" 
             Text='<%# Bind("State") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewStreetAddressFooterTemplateState"
             Text='<%# Bind("State") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="Zip Code"
           SortExpression="ZipCode"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewStreetAddressItemTemplateZipCode" 
             Text='<%# Eval("ZipCode") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewStreetAddressEditItemTemplateZipCode" 
             Text='<%# Bind("ZipCode") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewStreetAddressFooterTemplateZipCode"
             Text='<%# Bind("ZipCode") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="Country"
           SortExpression="Country"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewStreetAddressItemTemplateCountry" 
             Text='<%# Eval("Country") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewStreetAddressEditItemTemplateCountry" 
             Text='<%# Bind("Country") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewStreetAddressFooterTemplateCountry"
             Text='<%# Bind("Country") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>
               
          <asp:TemplateField
           HeaderText="Dated"
           SortExpression="Dated"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewStreetAddressItemTemplateDated" 
             Text='<%# Eval("Dated", "{0:s}") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewStreetAddressEditItemTemplateDated" 
             Text='<%# Bind("Dated") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewStreetAddressFooterTemplateDated"
             Text='<%# Bind("Dated") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="streetAddressID"
           SortExpression="streetAddressID"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewStreetAddressItemTemplatestreetAddressID" 
             Text='<%# Eval("streetAddressID") %>'
            />
           </ItemTemplate>
<%--
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewStreetAddressEditItemTemplatestreetAddressID" 
             Text='<%# Bind("streetAddressID") %>'
            />
           </EditItemTemplate>
--%>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewStreetAddressFooterTemplatestreetAddressID"
             Text='<%# Bind("streetAddressID") %>'
            />
            <asp:Button 
             Runat="Server"           
             ID="ButtonGridViewStreetAddressFooterTemplateAdd"
             OnClick="GridViewStreetAddressInsert"
             Text="Add"
            />
           </FooterTemplate>
          </asp:TemplateField>
         
         </Columns>
         <pagersettings 
          mode="Numeric"
          position="Bottom"           
          pagebuttoncount="10"
         />
         <pagerstyle 
          backcolor="LightBlue"
          height="30px"
          verticalalign="Bottom"
          horizontalalign="Center"
         />
        </asp:GridView>
       </td>
      </tr>
     </tbody>    
    </table>

    <table align="center" border="0">
     <tbody> 
      <tr align="center">
       <td align="center">
          <asp:FormView 
           runat="server"
           id="FormViewStreetAddress"
           AllowPaging="true"
           DataKeyNames="streetAddressID"
           DataSourceID="SqlDataSourceStreetAddress"
           DefaultMode="Insert"
           OnItemInserted="FormView_ItemInserted"

           Visible=false
          >
           <InsertItemTemplate>
            <table>
             <theader>
              <tr>
               <th>Address Line 1</th>
               <th>City</th>
               <th>State</th>
               <th>Zip Code</th>
               <th>Country</th>
               <th>Dated</th>
               <th>streetAddressID</th>
              </tr>
             </theader>
             <tbody>
              <tr>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewStreetAddressInsertItemTemplateAddressLine1" 
                 Text='<%# Bind("AddressLine1") %>'
                />
               </td>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewStreetAddressInsertItemTemplateCity" 
                 Text='<%# Bind("City") %>'
                />
               </td>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewStreetAddressInsertItemTemplateState" 
                 Text='<%# Bind("State") %>'
                />
               </td>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewStreetAddressInsertItemTemplateZipCode" 
                 Text='<%# Bind("ZipCode") %>'
                />
               </td>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewStreetAddressInsertItemTemplateCountry" 
                 Text='<%# Bind("Country") %>'
                />
               </td>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewStreetAddressInsertItemTemplateDated" 
                 Text='<%# Bind("Dated") %>'
                />
               </td>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewStreetAddressInsertItemTemplatestreetAddressID" 
                 Text='<%# Bind("streetAddressID") %>'
                />
               </td>
               <td>
                <asp:Button 
                 runat="server"
                 id="ButtonFormViewStreetAddress"  
                 onclick="ButtonFormViewStreetAddressInsert_Click"
                 Text="Add"
                />
                <%--
                <asp:linkbutton 
                 runat="server"
                 id="LinkButtonInsert"
                 text="Insert"
                 commandname="Insert"
                />
                <asp:linkbutton 
                 runat="server"
                 id="LinkButtonCancel"
                 text="Cancel"
                 commandname="Cancel"
                />
                --%>
               </td>
              </tr> 
             </tbody>
            </table>       
           </InsertItemTemplate>
          </asp:FormView>
       </td>
      </tr>
     </tbody>    
    </table>

    <table align="center" border="0">
     <tbody> 
      <tr align="center">
       <td align="center">
        <asp:SqlDataSource
         ID="SqlDataSourceContactRelated"
         Runat="server"
         ConnectionString="<%$ ConnectionStrings:WordEngineering %>"
         DeleteCommand="DELETE ContactRelated WHERE contactRelatedID = @contactRelatedID"
         InsertCommand="EXEC uspContactRelatedInsert @contactRelatedID, @dated, @contactId, @relatedId, @relationship, @commentary"
         SelectCommand="SELECT contactRelatedID, dated, contactId, relatedId, relationship, commentary FROM ContactRelated WHERE contactId = @contactId ORDER BY Dated DESC, contactRelatedID DESC "
         UpdateCommand="UPDATE ContactRelated SET dated = @dated, relatedId = @relatedId, relationship = @relationship, commentary = @commentary WHERE contactRelatedID = @contactRelatedID"
        >
         <insertparameters>
          <asp:parameter name="contactRelatedID" ConvertEmptyStringToNull=true Type="Int32" />
          <asp:parameter name="dated" ConvertEmptyStringToNull=true Type="DateTime" />
          <asp:ControlParameter Name="contactId" ControlId="GridViewContact" PropertyName="SelectedValue" />
          <asp:parameter name="relatedId" ConvertEmptyStringToNull=true Type="Int32" />
          <asp:parameter name="relationship" ConvertEmptyStringToNull=true Type="string" />
		  <asp:parameter name="commentary" ConvertEmptyStringToNull=true Type="string" />
         </insertparameters>
         <selectparameters>
          <asp:ControlParameter Name="contactId" ControlId="GridViewContact" PropertyName="SelectedValue" />
         </selectparameters>
        </asp:SqlDataSource>

        <asp:GridView
         id="GridViewContactRelated" 
         runat="server" 
         AllowPaging=True
         AllowSorting=True 
         AutoGenerateColumns=False
         AutoGenerateDeleteButton=True
         AutoGenerateEditButton=True
         AutoGenerateSelectButton=True        
         DataKeyNames="contactRelatedID"
         DataSourceID="SqlDataSourceContactRelated"
         OnPreRender="GridView_PreRender"
         OnRowUpdated="GridView_RowUpdated"
         SelectedIndex=0        
         ShowFooter=True
        >
         <HeaderStyle
          BackColor='#CCCC99'/>

         <RowStyle
          BackColor='#eeeeee'/>
			
         <AlternatingRowStyle
          BackColor='#ffffe8'/>

         <Columns>

          <asp:TemplateField
           HeaderText="RelatedId"
           SortExpression="RelatedId"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewContactRelatedItemTemplateRelatedId" 
             Text='<%# Eval("RelatedId") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactRelatedEditItemTemplateRelatedId" 
             Text='<%# Bind("RelatedId") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactRelatedFooterTemplateRelatedId"
             Text='<%# Bind("RelatedId") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="Relationship"
           SortExpression="Relationship"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewContactRelatedItemTemplateRelationship" 
             Text='<%# Eval("Relationship") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactRelatedEditItemTemplateRelationship" 
             Text='<%# Bind("Relationship") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactRelatedFooterTemplateRelationship"
             Text='<%# Bind("Relationship") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="Commentary"
           SortExpression="Commentary"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewContactRelatedItemTemplateCommentary" 
             Text='<%# Eval("Commentary") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactRelatedEditItemTemplateCommentary" 
             Text='<%# Bind("Commentary") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactRelatedFooterTemplateCommentary"
             Text='<%# Bind("Commentary") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="Dated"
           SortExpression="Dated"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewContactRelatedItemTemplateDated" 
             Text='<%# Eval("Dated", "{0:s}") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactRelatedEditItemTemplateDated" 
             Text='<%# Bind("Dated") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactRelatedFooterTemplateDated"
             Text='<%# Bind("Dated") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="contactRelatedID"
           SortExpression="contactRelatedID"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewContactRelatedItemTemplatecontactRelatedID" 
             Text='<%# Eval("contactRelatedID") %>'
            />
           </ItemTemplate>
<%--
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactRelatedEditItemTemplatecontactRelatedID" 
             Text='<%# Bind("contactRelatedID") %>'
            />
           </EditItemTemplate>
--%>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactRelatedFooterTemplatecontactRelatedID"
             Text='<%# Bind("contactRelatedID") %>'
            />
            <asp:Button 
             Runat="Server"           
             ID="ButtonGridViewContactRelatedFooterTemplateAdd"
             OnClick="GridViewContactRelatedInsert"
             Text="Add"
            />
           </FooterTemplate>
          </asp:TemplateField>
         
         </Columns>
         <pagersettings 
          mode="Numeric"
          position="Bottom"           
          pagebuttoncount="10"
         />
         <pagerstyle 
          backcolor="LightBlue"
          height="30px"
          verticalalign="Bottom"
          horizontalalign="Center"
         />
        </asp:GridView>
       </td>
      </tr>
     </tbody>    
    </table>

    <table align="center" border="0">
     <tbody> 
      <tr align="center">
       <td align="center">
          <asp:FormView 
           runat="server"
           id="FormViewContactRelated"
           AllowPaging="true"
           DataKeyNames="contactRelatedID"
           DataSourceID="SqlDataSourceContactRelated"
           DefaultMode="Insert"
           OnItemInserted="FormView_ItemInserted"
           Visible=false
          >
           <InsertItemTemplate>
            <table>
             <theader>
              <tr>
               <th>Related Id</th>
               <th>Relationship</th>
               <th>Commentary</th>
               <th>Dated</th>
               <th>contactRelatedID</th>
              </tr>
             </theader>
             <tbody>
              <tr>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewContactRelatedInsertItemTemplateRelatedId" 
                 Text='<%# Bind("RelatedId") %>'
                />
               </td>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewContactRelatedInsertItemTemplateRelationship" 
                 Text='<%# Bind("Relationship") %>'
                />
               </td>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewContactRelatedInsertItemTemplateCommentary" 
                 Text='<%# Bind("Commentary") %>'
                />
               </td>
               </td>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewContactRelatedInsertItemTemplateDated" 
                 Text='<%# Bind("Dated") %>'
                />
               </td>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewContactRelatedInsertItemTemplatecontactRelatedID" 
                 Text='<%# Bind("contactRelatedID") %>'
                />
               </td>
               <td>
                <asp:Button 
                 runat="server"
                 id="ButtonFormViewContactRelated"  
                 onclick="ButtonFormViewContactRelatedInsert_Click"
                 Text="Add"
                />
                <%--
                <asp:linkbutton 
                 runat="server"
                 id="LinkButtonInsert"
                 text="Insert"
                 commandname="Insert"
                />
                <asp:linkbutton 
                 runat="server"
                 id="LinkButtonCancel"
                 text="Cancel"
                 commandname="Cancel"
                />
                --%>
               </td>
              </tr> 
             </tbody>
            </table>       
           </InsertItemTemplate>
          </asp:FormView>
       </td>
      </tr>
     </tbody>    
    </table>
	
    <table align="center" border="0">
     <tbody> 
      <tr align="center">
       <td align="center">
        <asp:SqlDataSource
         ID="SqlDataSourceCaseBasedReasoning"
         Runat="server"
         ConnectionString="<%$ ConnectionStrings:WordEngineering %>"
         DeleteCommand="DELETE CaseBasedReasoning WHERE caseBasedReasoningID = @caseBasedReasoningID"
         InsertCommand="EXEC uspCaseBasedReasoningInsert @caseBasedReasoningID, @dated, @ContactID, @commentary, @expense, @income"
         SelectCommand="SELECT caseBasedReasoningID, dated, commentary, expense, income FROM CaseBasedReasoning WHERE ContactID = @ContactID ORDER BY Dated DESC, caseBasedReasoningID DESC"
         UpdateCommand="UPDATE CaseBasedReasoning SET dated = @dated, commentary = @commentary, expense = @expense, income = @income WHERE caseBasedReasoningID = @caseBasedReasoningID"
        >
         <insertparameters>
          <asp:parameter name="caseBasedReasoningID" ConvertEmptyStringToNull=true Type="Int32" />
          <asp:parameter name="dated" ConvertEmptyStringToNull=true Type="DateTime" />
          <asp:ControlParameter Name="ContactID" ControlId="GridViewContact" PropertyName="SelectedValue" />
          <asp:parameter name="commentary" ConvertEmptyStringToNull=true Type="string" />
          <asp:parameter name="expense" ConvertEmptyStringToNull=true Type="Double" />
          <asp:parameter name="income" ConvertEmptyStringToNull=true Type="Double" />
         </insertparameters>
         <selectparameters>
          <asp:ControlParameter Name="ContactID" ControlId="GridViewContact" PropertyName="SelectedValue" />
         </selectparameters>
        </asp:SqlDataSource>

        <asp:GridView
         id="GridViewCaseBasedReasoning" 
         runat="server" 
         AllowPaging=True
         AllowSorting=True 
         AutoGenerateColumns=False
         AutoGenerateDeleteButton=True
         AutoGenerateEditButton=True
         AutoGenerateSelectButton=True        
         DataKeyNames="caseBasedReasoningID"
         DataSourceID="SqlDataSourceCaseBasedReasoning"
         OnPreRender="GridView_PreRender"
         OnRowUpdated="GridView_RowUpdated"
         SelectedIndex=0        
         ShowFooter=True
        >
         <HeaderStyle
          BackColor='#CCCC99'/>

         <RowStyle
          BackColor='#eeeeee'/>
			
         <AlternatingRowStyle
          BackColor='#ffffe8'/>

         <Columns>

          <asp:TemplateField
           HeaderText="Commentary"
           SortExpression="Commentary"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewCaseBasedReasoningItemTemplateCommentary" 
             Text='<%# Eval("Commentary") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewCaseBasedReasoningEditItemTemplateCommentary" 
             Text='<%# Bind("Commentary") %>'
             TextMode="MultiLine"
             Columns="50"
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewCaseBasedReasoningFooterTemplateCommentary"
             Text='<%# Bind("Commentary") %>'
             TextMode="MultiLine"
             Columns="50"
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="Expense"
           SortExpression="Expense"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewCaseBasedReasoningItemTemplateExpense" 
             Text='<%# Eval("Expense", "{0:C}") %>'
			/>
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewCaseBasedReasoningEditItemTemplateExpense" 
             Text='<%# Bind("Expense") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewCaseBasedReasoningFooterTemplateExpense"
             Text='<%# Bind("Expense") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="Income"
           SortExpression="Income"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewCaseBasedReasoningItemTemplateIncome" 
             Text='<%# Eval("Income", "{0:C}") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewCaseBasedReasoningEditItemTemplateIncome" 
             Text='<%# Bind("Income") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewCaseBasedReasoningFooterTemplateIncome"
             Text='<%# Bind("Income") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="Dated"
           SortExpression="Dated"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewCaseBasedReasoningItemTemplateDated" 
             Text='<%# Eval("Dated", "{0:s}") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewCaseBasedReasoningEditItemTemplateDated" 
             Text='<%# Bind("Dated") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewCaseBasedReasoningFooterTemplateDated"
             Text='<%# Bind("Dated") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="caseBasedReasoningID"
           SortExpression="caseBasedReasoningID"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewCaseBasedReasoningItemTemplatecaseBasedReasoningID" 
             Text='<%# Eval("caseBasedReasoningID") %>'
            />
           </ItemTemplate>
<%--
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewCaseBasedReasoningEditItemTemplatecaseBasedReasoningID" 
             Text='<%# Bind("caseBasedReasoningID") %>'
            />
           </EditItemTemplate>
--%>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewCaseBasedReasoningFooterTemplatecaseBasedReasoningID"
             Text='<%# Bind("caseBasedReasoningID") %>'
            />
            <asp:Button 
             Runat="Server"           
             ID="ButtonGridViewCaseBasedReasoningFooterTemplateAdd"
             OnClick="GridViewCaseBasedReasoningInsert"
             Text="Add"
            />
           </FooterTemplate>
          </asp:TemplateField>
         
         </Columns>
         <pagersettings 
          mode="Numeric"
          position="Bottom"           
          pagebuttoncount="10"
         />
         <pagerstyle 
          backcolor="LightBlue"
          height="30px"
          verticalalign="Bottom"
          horizontalalign="Center"
         />
        </asp:GridView>
       </td>
      </tr>
     </tbody>    
    </table>

    <table align="center" border="0">
     <tbody> 
      <tr align="center">
       <td align="center">
          <asp:FormView 
           runat="server"
           id="FormViewCaseBasedReasoning"
           AllowPaging="true"
           DataKeyNames="caseBasedReasoningID"
           DataSourceID="SqlDataSourceCaseBasedReasoning"
           DefaultMode="Insert"
           OnItemInserted="FormView_ItemInserted"

           Visible=false
          >
           <InsertItemTemplate>
            <table>
             <theader>
              <tr>
               <th>Commentary</th>
               <th>Expense</th>
               <th>Income</th>
               <th>Dated</th>
               <th>caseBasedReasoningID</th>
              </tr>
             </theader>
             <tbody>
              <tr>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewCaseBasedReasoningInsertItemTemplateCommentary" 
                 Text='<%# Bind("Commentary") %>'
                />
               </td>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewCaseBasedReasoningInsertItemTemplateExpense" 
                 Text='<%# Bind("Expense") %>'
                />
               </td>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewCaseBasedReasoningInsertItemTemplateIncome" 
                 Text='<%# Bind("Income") %>'
                />
               </td>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewCaseBasedReasoningInsertItemTemplateDated" 
                 Text='<%# Bind("Dated") %>'
                />
               </td>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewCaseBasedReasoningInsertItemTemplatecaseBasedReasoningID" 
                 Text='<%# Bind("caseBasedReasoningID") %>'
                />
               </td>
               <td>
                <asp:Button 
                 runat="server"
                 id="ButtonFormViewCaseBasedReasoning"  
                 onclick="ButtonFormViewCaseBasedReasoningInsert_Click"
                 Text="Add"
                />
                <%--
                <asp:linkbutton 
                 runat="server"
                 id="LinkButtonInsert"
                 text="Insert"
                 commandname="Insert"
                />
                <asp:linkbutton 
                 runat="server"
                 id="LinkButtonCancel"
                 text="Cancel"
                 commandname="Cancel"
                />
                --%>
               </td>
              </tr> 
             </tbody>
            </table>       
           </InsertItemTemplate>
          </asp:FormView>
       </td>
      </tr>
     </tbody>    
    </table>

    <table align="center" border="0">
     <tbody> 
      <tr align="center">
       <td align="center">
        <asp:SqlDataSource
         ID="SqlDataSourceContactImage"
         Runat="server"
         ConnectionString="<%$ ConnectionStrings:ElectronicCopy %>"
         DeleteCommand="DELETE ContactImage WHERE contactImageID = @contactImageID"
         InsertCommand="EXEC uspContactImageUpdate @contactImageID, @dated, @ContactID, @imageSource"
         SelectCommand="SELECT contactImageID, dated, imageSource, imageType FROM ContactImage WHERE ContactID = @ContactID ORDER BY Dated DESC, contactImageID DESC"
         UpdateCommand="UPDATE ContactImage SET dated = @dated WHERE contactImageID = @contactImageID"
        >
         <insertparameters>
          <asp:parameter name="contactImageID" ConvertEmptyStringToNull=true Type="Int32" />
          <asp:parameter name="dated" ConvertEmptyStringToNull=true Type="DateTime" />
          <asp:ControlParameter Name="ContactID" ControlId="GridViewContact" PropertyName="SelectedValue" />
          <asp:parameter name="imageSource" ConvertEmptyStringToNull=true Type="string" />
         </insertparameters>
         <selectparameters>
          <asp:ControlParameter Name="ContactID" ControlId="GridViewContact" PropertyName="SelectedValue" />
         </selectparameters>
         <updateparameters>
          <asp:parameter name="contactImageID" ConvertEmptyStringToNull=true Type="Int32" />
          <asp:parameter name="dated" ConvertEmptyStringToNull=true Type="DateTime" />
          <asp:ControlParameter Name="ContactID" ControlId="GridViewContact" PropertyName="SelectedValue" />
          <asp:parameter name="imageSource" ConvertEmptyStringToNull=true Type="string" />
         </updateparameters>
        </asp:SqlDataSource>

        <asp:GridView
         id="GridViewContactImage" 
         runat="server" 
         AllowPaging=True
         AllowSorting=True 
         AutoGenerateColumns=False
         AutoGenerateDeleteButton=True
         AutoGenerateEditButton=True
         AutoGenerateSelectButton=True        
         DataKeyNames="contactImageID"
         DataSourceID="SqlDataSourceContactImage"
         OnPreRender="GridView_PreRender"
         OnRowUpdating="GridView_RowUpdating"
         OnRowUpdated="GridView_RowUpdated"
         SelectedIndex=0        
         ShowFooter=True
        >
         <HeaderStyle
          BackColor='#CCCC99'/>

         <RowStyle
          BackColor='#eeeeee'/>
			
         <AlternatingRowStyle
          BackColor='#ffffe8'/>

         <Columns>
<%--
          <asp:buttonField 
           buttontype="Link" 
           commandname="ButtonFieldGridViewContactRender"
           text="Render"/>
--%>
          <asp:TemplateField
           HeaderText="Source"
           SortExpression="ImageSource"
          >
           <ItemTemplate>
            <asp:HyperLink
             Runat="Server"
             id="HyperLinkGridViewContactImageItemTemplateImageSource" 
             NavigateUrl='<%# "RenderImage.aspx?ContentColumn=ImageContent&SourceColumn=ImageSource&TypeColumn=ImageType&DataSource=ContactImage&contactImageID=" + Eval("contactImageID") %>'
             Text='<%# Eval("ImageSource") %>'
             Target="_blank"
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:FileUpload 
             Runat="server"
             ID="FileUploadGridViewContactImageEditItemTemplateImageSource"
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:FileUpload 
             Runat="server"
             ID="FileUploadGridViewContactImageFooterTemplateImageSource"
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="Dated"
           SortExpression="Dated"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewContactImageItemTemplateDated" 
             Text='<%# Eval("Dated", "{0:s}") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactImageEditItemTemplateDated" 
             Text='<%# Bind("Dated") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactImageFooterTemplateDated"
             Text='<%# Bind("Dated") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="contactImageID"
           SortExpression="contactImageID"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewContactImageItemTemplatecontactImageID" 
             Text='<%# Eval("contactImageID") %>'
            />
           </ItemTemplate>
<%--
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactImageEditItemTemplatecontactImageID" 
             Text='<%# Bind("contactImageID") %>'
            />
           </EditItemTemplate>
--%>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactImageFooterTemplatecontactImageID"
             Text='<%# Bind("contactImageID") %>'
            />
            <asp:Button 
             Runat="Server"           
             ID="ButtonGridViewContactImageFooterTemplateAdd"
             OnClick="GridViewContactImageInsert"
             Text="Add"
            />
           </FooterTemplate>
          </asp:TemplateField>
         
         </Columns>
         <pagersettings 
          mode="Numeric"
          position="Bottom"           
          pagebuttoncount="10"
         />
         <pagerstyle 
          backcolor="LightBlue"
          height="30px"
          verticalalign="Bottom"
          horizontalalign="Center"
         />
        </asp:GridView>
       </td>
      </tr>
     </tbody>    
    </table>

    <table align="center" border="0">
     <tbody> 
      <tr align="center">
       <td align="center">
          <asp:FormView 
           runat="server"
           id="FormViewContactImage"
           AllowPaging="true"
           DataKeyNames="contactImageID"
           DataSourceID="SqlDataSourceContactImage"
           DefaultMode="Insert"
           OnItemInserted="FormView_ItemInserted"

           Visible=false
          >
           <InsertItemTemplate>
            <table>
             <theader>
              <tr>
               <th>Image</th>
               <th>Dated</th>
               <th>contactImageID</th>
              </tr>
             </theader>
             <tbody>
              <tr>
               <td>
                <asp:FileUpload 
                 Runat="server"
                 ID="FileUploadFormViewContactImageInsertItemTemplateImageSource"
                />
               </td>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewContactImageInsertItemTemplateDated" 
                 Text='<%# Bind("Dated") %>'
                />
               </td>
               <td>
                <asp:textbox 
                 runat="server"
                 id="TextBoxFormViewContactImageInsertItemTemplatecontactImageID" 
                 Text='<%# Bind("contactImageID") %>'
                />
               </td>
               <td>
                <asp:Button 
                 runat="server"
                 id="ButtonFormViewContactImage"  
                 onclick="ButtonFormViewContactImageInsert_Click"
                 Text="Add"
                />
                <%--
                 <asp:linkbutton 
                 runat="server"
                 id="LinkButtonInsert"
                 text="Insert"
                 commandname="Insert"
                />
                <asp:linkbutton 
                 runat="server"
                 id="LinkButtonCancel"
                 text="Cancel"
                 commandname="Cancel"
                />
                --%>
               </td>
              </tr> 
             </tbody>
            </table>       
           </InsertItemTemplate>
          </asp:FormView>
       </td>
      </tr>
     </tbody>    
    </table>
    
    <table align="center" border="0">
     <tbody> 
      <tr align="center">
       <td align="center">
        <asp:Literal 
         id="LiteralFeedback" 
         runat="server" 
         EnableViewState=False
        />
       </td>
      </tr>
     </tbody>    
    </table>

   </form>
  </asp:Panel>
    <script>
		//2014-08-24 http://stackoverflow.com/questions/4793955/how-to-add-a-confirm-delete-option-in-asp-net-gridview
		function confirmDelete()
		{
			var anchors=document.getElementsByTagName("a");
			for (var index = 0, count = anchors.length; index < count; ++index)
			{
				var currentElement = anchors[index];
				var elementName = currentElement.innerHTML;
				if (elementName === "Delete")
				{
					anchors[index].addEventListener
					(
						"click",
						function (event) 
						{ 
							if (!confirm("Are you sure you want to delete this record?"))
							{ 
								event.preventDefault(); 
							} 
						},
						false
					);					
				}	
			}	
		}
		
		window.addEventListener("load", confirmDelete, false);
	</script>
  
 </body>
</html>
