<%@ Page 
 Language="C#" 
 debug=true
%>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" 
"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" >
 <head runat="Server" id="HeadId">
  <title runat="Server" id="TitleId">Date of Birth</title>
 </head>
 <body runat="server" id="BodyId">
  <asp:Panel
   runat="server"
   id="PanelId"
  >
   <form 
    ID="FormId" 
    runat="server"
    enctype="multipart/form-data"    
    autocomplete="on"
   >
    <table align="center" border="0">
     <tbody>
      <tr align="center">
       <td>
        <asp:SqlDataSource
         ID="SqlDataSourceContact"
         Runat="server"
         ConnectionString="<%$ ConnectionStrings:WordEngineering %>"
         SelectCommand="SELECT CaseBasedReasoning.Dated AS dated, Contact.SequenceOrderId AS sequenceOrderId, FirstName, LastName, OtherName, Title, Company, Contact.Commentary FROM Contact INNER JOIN CaseBasedReasoning ON Contact.SequenceOrderId = CaseBasedReasoning.ContactId WHERE CaseBasedReasoning.Commentary = 'Date of Birth (DOB)' ORDER BY MONTH(CaseBasedReasoning.Dated), DAY(CaseBasedReasoning.Dated)"
        >
        </asp:SqlDataSource>

        <asp:GridView
         id="GridViewContact" 
         runat="server" 
         AllowPaging=True
         AllowSorting=True 
         AutoGenerateColumns=False
         AutoGenerateDeleteButton=False
         AutoGenerateEditButton=False
         AutoGenerateSelectButton=False
         DataKeyNames="sequenceOrderId"
         DataSourceID="SqlDataSourceContact"
         SelectedIndex=0
         ShowFooter=True
        >
         <HeaderStyle
          BackColor='#CCCC99'/>

         <RowStyle
          BackColor='#eeeeee'/>
			
         <AlternatingRowStyle
          BackColor='#ffffe8'/>

         <Columns>

          <asp:TemplateField
           HeaderText="Dated"
           SortExpression="Dated"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewContactItemTemplateDated" 
             Text='<%# Eval("Dated", "{0:d}") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactEditItemTemplateDated" 
             Text='<%# Bind("Dated") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactFooterTemplateDated"
             Text='<%# Bind("Dated") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>
		 
          <asp:TemplateField
           HeaderText="First Name"
           SortExpression="FirstName"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewContactItemTemplateFirstName" 
             Text='<%# Eval("FirstName") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactEditItemTemplateFirstName" 
             Text='<%# Bind("FirstName") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactFooterTemplateFirstName"
             Text='<%# Bind("FirstName") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="Last Name"
           SortExpression="LastName"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewContactItemTemplateLastName" 
             Text='<%# Eval("LastName") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactEditItemTemplateLastName" 
             Text='<%# Bind("LastName") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactFooterTemplateLastName"
             Text='<%# Bind("LastName") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="Other Name"
           SortExpression="OtherName"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewContactItemTemplateOtherName" 
             Text='<%# Eval("OtherName") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactEditItemTemplateOtherName" 
             Text='<%# Bind("OtherName") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactFooterTemplateOtherName"
             Text='<%# Bind("OtherName") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="Title"
           SortExpression="Title"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewContactItemTemplateTitle" 
             Text='<%# Eval("Title") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactEditItemTemplateTitle" 
             Text='<%# Bind("Title") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactFooterTemplateTitle"
             Text='<%# Bind("Title") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="Company"
           SortExpression="Company"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewContactItemTemplateCompany" 
             Text='<%# Eval("Company") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactEditItemTemplateCompany" 
             Text='<%# Bind("Company") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactFooterTemplateCompany"
             Text='<%# Bind("Company") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="Commentary"
           SortExpression="Commentary"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewContactItemTemplateCommentary" 
             Text='<%# Eval("Commentary") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactEditItemTemplateCommentary" 
             Text='<%# Bind("Commentary") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactFooterTemplateCommentary"
             Text='<%# Bind("Commentary") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="SequenceOrderId"
           SortExpression="SequenceOrderId"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewContactItemTemplateSequenceOrderId" 
             Text='<%# Eval("SequenceOrderId") %>'
            />
           </ItemTemplate>
<%--
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactEditItemTemplateSequenceOrderId" 
             Text='<%# Bind("SequenceOrderId") %>'
            />
           </EditItemTemplate>
--%>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewContactFooterTemplateSequenceOrderId"
             Text='<%# Bind("SequenceOrderId") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>
         
         </Columns>
         <pagersettings 
          mode="Numeric"
          position="Bottom"           
          pagebuttoncount="10"
         />
         <pagerstyle 
          backcolor="LightBlue"
          height="30px"
          verticalalign="Bottom"
          horizontalalign="Center"
         />
        </asp:GridView>
       </td>
      </tr>
     </tbody>
    </table>

    <table align="center" border="0">
     <tbody> 
      <tr align="center">
       <td align="center">
        <asp:Literal 
         id="LiteralFeedback" 
         runat="server" 
         EnableViewState=False
        />
       </td>
      </tr>
     </tbody>    
    </table>

   </form>
  </asp:Panel>
 </body>
</html>