<%@ Page 
 Language="C#" 
 debug=true
 Inherits="WordEngineering.ItsCalledTheSetupScreenOfScreenOnePage"
%>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" 
"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" >
 <head runat="Server" id="HeadItsCalledTheSetupScreenOfScreenOne">
  <title runat="Server" id="TitleItsCalledTheSetupScreenOfScreenOne">Its called the Setup Screen of Screen One</title>
 </head>
 <body runat="server" id="BodyItsCalledTheSetupScreenOfScreenOne">
  <asp:Panel
   runat="server"
   id="PanelItsCalledTheSetupScreenOfScreenOne"
  >
   <form 
    ID="FormItsCalledTheSetupScreenOfScreenOne" 
    runat="server"
    enctype="multipart/form-data"    
    autocomplete="on"
    defaultbutton="ButtonSubmit"
    defaultfocus="TextBoxScreenOne"
   >
    <table align="center" border="0">
     <tbody>
      <tr align="center">
       <td align="center" colspan=4>
        Search Query
       </td>
      </tr>

      <tr align="center">
       <td align="left">
        <asp:Label
         runat="server"       
         id="LabelScreenOne"
         Text="Screen One:"
         AccessKey="S"
         AssociatedControlId="TextBoxScreenOne"
        />
       </td>
       <td align="left">
        <asp:TextBox
         runat="Server"
         ID="TextBoxScreenOne"
         TabIndex="1"
        />        
       </td>
      </tr>

      <tr align="center">       
       <td align="left">
        <asp:Label
         runat="server"
         id="LabelDated"
         Text="Dated:"
         AccessKey="R"
         AssociatedControlId="TextBoxDatedFrom"
        />
       </td>
       <td align="left">       
        <asp:TextBox
         runat="Server"
         ID="TextBoxDatedFrom"
         TabIndex="2"
        />
        -
        <asp:TextBox
         runat="Server"
         ID="TextBoxDatedTo"
         TabIndex="3"
        />        
       </td>
      </tr>

      <tr align="center">
       <td align="center" colspan="4">
        <asp:Button runat="server" id="ButtonSubmit"  onclick="ButtonSubmit_Click"  Text="Submit" TabIndex="10" />
        <asp:Button runat="server" id="ButtonReset"   onclick="ButtonReset_Click"   Text="Reset"  TabIndex="11" />
       </td>      
       </tr>
     </tbody>
    </table>

    <table align="center" border="0">
     <tbody>
      <tr align="center">
       <td>
        <asp:SqlDataSource
         ID="SqlDataSourceItsCalledTheSetupScreenOfScreenOne"
         Runat="server"
         ConnectionString="<%$ ConnectionStrings:WordEngineering %>"
         DeleteCommand="DELETE ItsCalledTheSetupScreenOfScreenOne WHERE sequenceOrderId = @sequenceOrderId"
         InsertCommand="EXEC uspItsCalledTheSetupScreenOfScreenOneInsert @sequenceOrderId, @dated, @ScreenOne"
         SelectCommand="EXEC uspItsCalledTheSetupScreenOfScreenOneSelect"
         UpdateCommand="UPDATE ItsCalledTheSetupScreenOfScreenOne SET Dated = @dated, ScreenOne = @ScreenOne WHERE sequenceOrderId = @sequenceOrderId"
        >
         <insertparameters>
          <asp:parameter name="sequenceOrderId" ConvertEmptyStringToNull=true Type="Int32" />
          <asp:parameter name="dated" ConvertEmptyStringToNull=true Type="DateTime" />
          <asp:parameter name="ScreenOne" ConvertEmptyStringToNull=true Type="string" />
         </insertparameters>
         <selectparameters>
<%--
          <asp:controlparameter name="ScreenOne" controlid="TextBoxScreenOne" PropertyName="Text" ConvertEmptyStringToNull=true Type="String" Direction="InputOutput" />
          <asp:controlparameter name="DatedFrom" controlid="TextBoxDatedFrom" PropertyName="Text" ConvertEmptyStringToNull=true Type="DateTime" Direction="InputOutput" />
          <asp:controlparameter name="DatedTo" controlid="TextBoxDatedTo" PropertyName="Text" ConvertEmptyStringToNull=true Type="DateTime" Direction="InputOutput" />
--%>          
         </selectparameters>
        </asp:SqlDataSource>

        <asp:GridView
         id="GridViewItsCalledTheSetupScreenOfScreenOne" 
         runat="server" 
         AllowPaging=True
         AllowSorting=True 
         AutoGenerateColumns=False
         AutoGenerateDeleteButton=True
         AutoGenerateEditButton=True
         DataKeyNames="sequenceOrderId"
         DataSourceID="SqlDataSourceItsCalledTheSetupScreenOfScreenOne"
         OnRowUpdated="GridView_RowUpdated"
         SelectedIndex=0
         ShowFooter=True
        >
         <HeaderStyle
          BackColor='#CCCC99'/>

         <RowStyle
          BackColor='#eeeeee'/>
			
         <AlternatingRowStyle
          BackColor='#ffffe8'/>

         <Columns>

          <asp:TemplateField
           HeaderText="Screen One"
           SortExpression="ScreenOne"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewItsCalledTheSetupScreenOfScreenOneItemTemplateScreenOne" 
             Text='<%# Eval("ScreenOne") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewItsCalledTheSetupScreenOfScreenOneEditItemTemplateScreenOne" 
             Text='<%# Bind("ScreenOne") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewItsCalledTheSetupScreenOfScreenOneFooterTemplateScreenOne"
             Text='<%# Bind("ScreenOne") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="Dated"
           SortExpression="Dated"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewItsCalledTheSetupScreenOfScreenOneItemTemplateDated" 
             Text='<%# Eval("Dated", "{0:d}") %>'
            />
           </ItemTemplate>
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewItsCalledTheSetupScreenOfScreenOneEditItemTemplateDated" 
             Text='<%# Bind("Dated") %>'
            />
           </EditItemTemplate>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewItsCalledTheSetupScreenOfScreenOneFooterTemplateDated"
             Text='<%# Bind("Dated") %>'
            />
           </FooterTemplate>
          </asp:TemplateField>

          <asp:TemplateField
           HeaderText="SequenceOrderId"
           SortExpression="SequenceOrderId"
          >
           <ItemTemplate>
            <asp:Label
             Runat="Server"
             id="LabelGridViewItsCalledTheSetupScreenOfScreenOneItemTemplateSequenceOrderId" 
             Text='<%# Eval("SequenceOrderId") %>'
            />
           </ItemTemplate>
<%--
           <EditItemTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewItsCalledTheSetupScreenOfScreenOneEditItemTemplateSequenceOrderId" 
             Text='<%# Bind("SequenceOrderId") %>'
            />
           </EditItemTemplate>
--%>
           <FooterTemplate>
            <asp:TextBox 
             Runat="Server"
             id="TextBoxGridViewItsCalledTheSetupScreenOfScreenOneFooterTemplateSequenceOrderId"
             Text='<%# Bind("SequenceOrderId") %>'
            />
            <asp:Button 
             Runat="Server"           
             ID="ButtonGridViewItsCalledTheSetupScreenOfScreenOneFooterTemplateAdd"
             OnClick="GridViewItsCalledTheSetupScreenOfScreenOneInsert"
             Text="Add"
            />
           </FooterTemplate>
          </asp:TemplateField>
         
         </Columns>
         <pagersettings 
          mode="Numeric"
          position="Bottom"           
          pagebuttoncount="10"
         />
         <pagerstyle 
          backcolor="LightBlue"
          height="30px"
          verticalalign="Bottom"
          horizontalalign="Center"
         />
        </asp:GridView>
       </td>
      </tr>
     </tbody>
    </table>
    
    <table align="center" border="0">
     <tbody> 
      <tr align="center">
       <td align="center">
        <asp:Literal 
         id="LiteralFeedback" 
         runat="server" 
         EnableViewState=False
        />
       </td>
      </tr>
     </tbody>    
    </table>

   </form>
  </asp:Panel>
 </body>
</html>