XCOPY AlphabetSequence.cs                                A:\Comforter\WordOfGod /C /D /E /I /R /S /Y
XCOPY BibleBookTitle.cs                                  A:\Comforter\WordOfGod /C /D /E /I /R /S /Y
XCOPY ScriptureReference.cs                              A:\Comforter\WordOfGod /C /D /E /I /R /S /Y
XCOPY ScriptureReferenceAlphabetSequence.cs              A:\Comforter\WordOfGod /C /D /E /I /R /S /Y
XCOPY ScriptureReferenceBookChapterVersePrePost.cs       A:\Comforter\WordOfGod /C /D /E /I /R /S /Y
XCOPY TheWord.cs                                         A:\Comforter\WordOfGod /C /D /E /I /R /S /Y
XCOPY TheWord.mak                                        A:\Comforter\WordOfGod /C /D /E /I /R /S /Y
XCOPY TheWordBuild.bat                                   A:\Comforter\WordOfGod /C /D /E /I /R /S /Y
XCOPY TheWordAlphabetSequence.cs                         A:\Comforter\WordOfGod /C /D /E /I /R /S /Y 
XCOPY TheWordPage.aspx.cs                                A:\Comforter\WordOfGod /C /D /E /I /R /S /Y  
XCOPY TheWordWebForm.aspx                                A:\Comforter\WordOfGod /C /D /E /I /R /S /Y  
XCOPY UtilityClass.cs                                    A:\Comforter\WordOfGod /C /D /E /I /R /S /Y 
XCOPY UtilityCollection.cs                               A:\Comforter\WordOfGod /C /D /E /I /R /S /Y 
XCOPY UtilityDatabase.cs                                 A:\Comforter\WordOfGod /C /D /E /I /R /S /Y 
XCOPY UtilityDirectory.cs                                A:\Comforter\WordOfGod /C /D /E /I /R /S /Y 
XCOPY UtilityEventLog.cs                                 A:\Comforter\WordOfGod /C /D /E /I /R /S /Y
XCOPY UtilityFile.cs                                     A:\Comforter\WordOfGod /C /D /E /I /R /S /Y 
XCOPY UtilitySerialize.cs                                A:\Comforter\WordOfGod /C /D /E /I /R /S /Y
XCOPY UtilityXml.cs                                      A:\Comforter\WordOfGod /C /D /E /I /R /S /Y